sudo: false
dist: 'trusty'

language: node_js
node_js:
  - "stable"

cache:
  directories:
    - $HOME/.npm
    - node_modules
    - ~/.cache

install:
  - npm i
  - cd client && npm i && cd ..

script:
  - npm run client
  - npm run cy
