sudo: false
dist: 'trusty'

language: node_js
node_js:
  - "stable"

cache:
  directories:
    - $HOME/.npm
    - node_modules
    - ~/.cache

install:
  - npm run setup

script:
  - npm run client
  - npm run cy
